require: rubocop-rspec

RSpec/BeforeAfterAll:
  Enabled: true

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'spec/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Layout/EndOfLine:
  Enabled: false

Layout/LineLength:
  Max: 120
  IgnoredPatterns: ['(\A|\s)#']

Lint/AmbiguousBlockAssociation:
  Enabled: false

Style/Documentation:
  Enabled: false

RSpec/EmptyLineAfterFinalLet:
  Enabled: false
